export const CONNECTION_FAILED = 'CONNECTION_FAILED';
export const UPDATE_BALANCE = 'UPDATE_BALANCE';
export const UPDATE_NETWORK = 'UPDATE_NETWORK';
export const UPDATE_ISRIGHTNETWORK = 'UPDATE_ISRIGHTNETWORK';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const UPDATE_WEB3 = 'UPDATE_WEB3';
export const UPDATE_HASMETAMASK = 'UPDATE_HASMETAMASK';
export const MINER_CONTRACT = 'MINER_CONTRACT';
export const MINE_CONTRACT = 'MINE_CONTRACT';
export const VAULT_CONTRACT = 'VAULT_CONTRACT';
export const DIAMOND_CONTRACT = 'DIAMOND_CONTRACT';
export const EVENT_CONTRACT = 'EVENT_CONTRACT';

export const TOGGLE_BOT = 'TOGGLE_BOT';
export const SET_BOT_SPEECH = 'SET_BOT_SPEECH';
export const SET_ENTERED_PASSWORD = 'SET_ENTERED_PASSWORD';
export const SET_LOADING = 'SET_LOADING';
export const ADD_ALERT = 'ADD_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const MINTDATA_SUCCESS = 'MINTDATA_SUCCESS';
export const MINTDATA_FAILED = 'MINTDATA_FAILED';
export const UPDATE_ISWHITELISTED = 'UPDATE_ISWHITELISTED';
